REQUEST_JSON_SOURCE_KEY = 'source'
REQUEST_JSON_DESTINATION_KEY = 'destination'
REQUEST_JSON_ALGORITHM_ID_KEY = 'algorithm_id'
REQUEST_JSON_PATH_PERCENTAGE_KEY = 'path_percentage'
REQUEST_JSON_MINIMIZE_ELEVATION_GAIN_KEY = 'minimize_elevation_gain'
REQUEST_JSON_TRANSPORTATION_MODE_KEY = 'transportation_mode'

COORDINATES_LATITUDE = 'lat'
COORDINATES_LONGITUDE = 'lng'
